

name: CI

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: chekcout repro
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: install depset
        run: |
          pip install -r requirements.txt
      - name: run test
        run: | 
          python main.py